---
- name: install git
  homebrew:
    name: git
    install_options: with-curl,with-openssl
    state: latest
  tags:
    - pkg
    - git

- name: install ~/.cvsignore
  copy:
    src: cvsignore
    dest: ~/.cvsignore
  tags:
    - git

- name: install ~/.gitconfig
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
  tags:
    - git
